---
- hosts: all
  become: true
  tasks:
    - name: Install apps on managed nodes
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - "{{ app_list }}"
    - name: Add gpg public key from the specified url
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present
    - name: Install docker 
      ansible.builtin.apt:
        pkg:
          - docker.io
