---
- hosts: all
  become: true
  tasks:
    #    - name: Install apps on managed nodes
    #      tags: ubuntu,initial_packages
    #      ansible.builtin.apt:
    #        name: "{{ item }}"
    #        state: present
    #        update_cache: yes
    #      with_items:
    #        - "{{ app_list }}"
    #    
    - name: Add gpg public key from the specified url
      tags: ubuntu,apt_key
      ansible.builtin.apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: present
    
    - name: Add specified repository into sources list
      tags: ubuntu,apt_repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present
    
    - name: Install docker and docker-buildx
      tags: ubuntu,docker
      ansible.builtin.apt:
        pkg:
          - docker.io
          - docker-buildx
      register: docker_package

    - name: start and enable service docker
      tags: ubuntu,docker,service
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started
      when: docker_package.changed

    - name: clone the simple-webapp-docker
      tags: ubuntu,git
      ansible.builtin.git:
        repo: 'https://github.com/Rony-dot/simple-webapp-docker.git'
        dest: /usr/local/share/simple-webapp-docker/
      register: git_repo

    - name: build docker image from the dockerfile of simple-webapp-docker
      tags: ubuntu,docker_image
      community.docker.docker_image_build:
        name: backend_image
        path: /usr/local/share/simple-webapp-docker
        dockerfile: Dockerfile
      when: git_repo.changed
      register: docker_image

    - name: create docker container from previously built docker image
      tags: ubuntu,docker_container
      community.docker.docker_container:
        name: backend_container
        image: backend_image
        exposed_ports:
          - 8081
        recreate: true
        published_ports:
          - "8082:8080"
      when: docker_image.changed
      register: docker_container
